version: "3"
services:
  frontend:
    build:
      context: ./frontend
    volumes: 
      - ./frontend:/src
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes: 
      - ./backend:/src
    ports:
      - "3001:3001"
